version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

  mysql:
      image: mysql:5.7
      container_name: mysql
      environment:
        MYSQL_ROOT_PASSWORD: root_password
        MYSQL_DATABASE: wordpress
        MYSQL_USER: wordpress
        MYSQL_PASSWORD: wordpress_password
      ports:
        - "3306:3306"
      volumes:
        - mysql_data:/var/lib/mysql
      networks:
        - app_network

volumes:
  redis_data:
  mysql_data:

networks:
  app_network:
    driver: bridge